application: timestimator
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /images
  static_dir: static/images
  
- url: .*
  script: main.py
  login: required
  
